"use client";

import { useState } from "react";
import type { ErpSite } from "@/domain/erp";
import type { CurrentErpUser } from "@/lib/erp/demo-session";

type Props = { site: ErpSite; user: CurrentErpUser };

const partners = [
  { code: "TA-018", name: "Công ty Du lịch Hoa Lư", owner: "Nguyễn Thu Hà", documents: "8/8", quote: "BG-2607-018 · Đã gửi", contract: "HĐ đến 31/12/2026", debt: "382 triệu", response: "12 phút", status: "Đang hoạt động", feedback: "Khách đoàn đề nghị nhận vé sớm hơn 15 phút.", next: "Nhân viên kinh doanh phản hồi trước 11:00" },
  { code: "NCC-011", name: "Ẩm thực Tràng An Xanh", owner: "Trần Quốc Việt", documents: "6/7", quote: "BG-2407-041 · Chờ duyệt", contract: "Phụ lục giá đang ký", debt: "146 triệu", response: "38 phút", status: "Thiếu hồ sơ", feedback: "Hai phản hồi về thời gian phục vụ suất đoàn.", next: "Bổ sung chứng nhận ATTP trước 16:00" },
  { code: "NCC-006", name: "Vận tải Minh Long", owner: "Phạm Ngọc Anh", documents: "9/9", quote: "BG-2207-009 · Đã chấp thuận", contract: "HĐ đến 30/06/2027", debt: "712 triệu", response: "9 phút", status: "Đúng cam kết", feedback: "Điểm đón mới giúp giảm 7 phút chờ xe.", next: "Đối soát 184 chuyến trước 17:30" },
] as const;

const comparisons = {
  week: ["1,86 tỷ", "+8,2%", "96%", "18 phút"],
  month: ["7,42 tỷ", "+5,6%", "94%", "24 phút"],
  year: ["62,8 tỷ", "+13,1%", "91%", "31 phút"],
} as const;

export function PartnerCommercialWorkspace({ site, user }: Props) {
  const [period, setPeriod] = useState<keyof typeof comparisons>("week");
  const [quoteMessage, setQuoteMessage] = useState("");
  const values = comparisons[period];

  function createQuote(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    setQuoteMessage(`Đã tạo báo giá nháp cho ${data.get("partner")} · ${data.get("product")} · ${data.get("quantity")} khách. Chờ ${user.role === "employee" ? "quản lý" : "người phụ trách"} duyệt.`);
  }

  return <div className="space-y-5">
    <section className="rounded-2xl border border-[#d8e0db] bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[0.17em] text-[#477565]">Hiệu quả đối tác · {site.shortName}</p><h2 className="mt-2 text-2xl font-black text-[#20342c]">Kinh doanh & nhà cung ứng</h2></div><div className="grid grid-cols-3 rounded-xl bg-[#f0f4f1] p-1">{(["week", "month", "year"] as const).map((item) => <button type="button" key={item} onClick={() => setPeriod(item)} className={`min-h-9 rounded-lg px-3 text-xs font-black ${period === item ? "bg-[#183f34] text-white" : "text-[#65756e]"}`}>{item === "week" ? "Tuần" : item === "month" ? "Tháng" : "Năm"}</button>)}</div></div><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Doanh số đối tác", values[0], values[1] + " so kỳ trước"], ["Hồ sơ đầy đủ", values[2], "Bình quân 3 năm: 89%"], ["Phản hồi trung bình", values[3], "SLA mục tiêu: 30 phút"], ["Công nợ đến hạn", "1,24 tỷ", "4 chứng từ chờ đối soát"]].map(([label, value, note]) => <article key={label} className="rounded-xl bg-[#f3f6f4] p-4"><p className="text-xs text-[#718078]">{label}</p><p className="mt-2 text-xl font-black text-[#253c33]">{value}</p><p className="mt-2 text-xs text-[#7b8881]">{note}</p></article>)}</div></section>

    {user.role !== "director" ? <form onSubmit={createQuote} className="rounded-2xl border border-[#d8e0db] bg-white p-5 shadow-sm sm:p-6"><p className="text-xs font-black uppercase tracking-[0.17em] text-[#8a5e30]">Báo giá mới</p><h2 className="mt-2 text-xl font-black text-[#20342c]">Tạo từ chính sách sản phẩm</h2><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4"><select required name="partner" className="min-h-11 rounded-xl border border-[#ced8d1] bg-white px-3"><option value="">Chọn đối tác *</option>{partners.map((item) => <option key={item.code}>{item.name}</option>)}</select><select required name="product" className="min-h-11 rounded-xl border border-[#ced8d1] bg-white px-3"><option value="">Chọn sản phẩm *</option><option>Vé đoàn tiêu chuẩn</option><option>Combo vé + xe/thuyền</option><option>Gói sự kiện theo đoàn</option></select><input required name="quantity" inputMode="numeric" className="min-h-11 rounded-xl border border-[#ced8d1] px-3" placeholder="Số khách *" /><input required name="validUntil" type="date" className="min-h-11 rounded-xl border border-[#ced8d1] px-3" /></div><textarea required name="terms" rows={2} className="mt-3 w-full rounded-xl border border-[#ced8d1] p-3" placeholder="Điều khoản thanh toán, hoàn đổi và công nợ *" /><button type="submit" className="mt-3 min-h-11 rounded-xl bg-[#183f34] px-5 text-sm font-black text-white">Tạo báo giá nháp</button>{quoteMessage ? <p role="status" className="mt-3 rounded-xl bg-[#e3f2eb] p-3 text-sm font-bold text-[#245e48]">{quoteMessage}</p> : null}</form> : null}

    <section className="rounded-2xl border border-[#d8e0db] bg-white p-5 shadow-sm sm:p-6"><p className="text-xs font-black uppercase tracking-[0.17em] text-[#477565]">Hồ sơ theo đơn vị</p><h2 className="mt-2 text-2xl font-black text-[#20342c]">Tài liệu, báo giá, công nợ và phản hồi</h2><div className="mt-5 space-y-3">{partners.map((partner) => <details key={partner.code} className="rounded-xl border border-[#e0e6e2] bg-white open:border-[#91aa9f]"><summary className="grid cursor-pointer list-none gap-2 p-4 sm:grid-cols-[0.45fr_1.2fr_0.75fr_auto] sm:items-center"><span className="text-xs font-black text-[#65776e]">{partner.code}</span><div><p className="font-black text-[#2d4138]">{partner.name}</p><p className="mt-1 text-xs text-[#7b8881]">Phụ trách: {partner.owner}</p></div><span className="text-xs font-bold">Hồ sơ {partner.documents}</span><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-black ${partner.status === "Thiếu hồ sơ" ? "bg-[#ffe4de] text-[#934336]" : "bg-[#dff1e8] text-[#246249]"}`}>{partner.status}</span></summary><div className="border-t border-[#e6ebe8] bg-[#f8faf8] p-4 sm:p-5"><dl className="grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-xs text-[#7b8881]">Báo giá</dt><dd className="mt-1 font-black">{partner.quote}</dd></div><div><dt className="text-xs text-[#7b8881]">Hợp đồng</dt><dd className="mt-1 font-black">{partner.contract}</dd></div><div><dt className="text-xs text-[#7b8881]">Công nợ</dt><dd className="mt-1 font-black">{partner.debt}</dd></div><div><dt className="text-xs text-[#7b8881]">Phản hồi khách</dt><dd className="mt-1 font-bold">{partner.feedback}</dd></div><div><dt className="text-xs text-[#7b8881]">Nhân viên phản hồi</dt><dd className="mt-1 font-bold">{partner.response}</dd></div><div><dt className="text-xs text-[#7b8881]">Việc tiếp theo</dt><dd className="mt-1 font-bold text-[#8a5138]">{partner.next}</dd></div></dl><div className="mt-4 rounded-xl border border-[#dfe6e2] bg-white p-3 text-xs text-[#64736c]">Tệp: ĐKKD.pdf · Hợp đồng.pdf · Báo giá.xlsx · Biên bản nghiệm thu.pdf · Nhật ký phản hồi khách</div></div></details>)}</div></section>

    <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-[#d8e0db] bg-white p-5"><p className="text-xs font-black uppercase tracking-[0.17em] text-[#477565]">Sản phẩm đang bán</p><div className="mt-4 space-y-3">{[["Vé đoàn tiêu chuẩn", "98.000 đ", "Hoa hồng 6% · Công nợ 15 ngày", "Mã SP: GROUP-STD · Tài khoản 5111 · Thuế và hạn mức chiết khấu lấy theo cấu hình hợp đồng."], ["Combo vé + xe/thuyền", "225.000 đ", "Hoa hồng 5% · Đổi giờ trước 60 phút", "Mã SP: COMBO-MOVE · Tách doanh thu vé và vận chuyển khi đối soát cuối ngày."], ["Gói sự kiện theo đoàn", "Theo báo giá", "Đặt cọc 50% · Chốt khách D-3", "Mã SP: EVENT-GROUP · Báo giá phải có ngân sách, lịch phục vụ và người duyệt trước khi gửi."]].map(([name, price, policy, detail]) => <details key={name} className="rounded-xl bg-[#f3f6f4] p-3 open:ring-1 open:ring-[#a9bdb3]"><summary className="cursor-pointer list-none"><div className="flex justify-between gap-3"><strong>{name}</strong><span>{price}</span></div><p className="mt-1 text-xs text-[#74827b]">{policy}</p></summary><p className="mt-3 border-t border-[#dfe6e2] pt-3 text-xs leading-5 text-[#5f7068]">{detail}</p></details>)}</div></article><article className="rounded-2xl border border-[#d8e0db] bg-white p-5"><p className="text-xs font-black uppercase tracking-[0.17em] text-[#477565]">Phản hồi cần kinh doanh xử lý</p><div className="mt-4 space-y-3">{[["FB-281", "Đoàn 42 khách · nhận vé chậm", "Đỗ Thị Lan · Hạn 11:00", "Khách gửi lúc 09:42 qua đối tác TA-018 · SLA còn 18 phút · Việc tiếp theo: xác nhận quầy nhận vé riêng và phản hồi lại đối tác."], ["FB-276", "Đề nghị thêm suất ăn trẻ em", "Nguyễn Thu Hà · Đã phản hồi", "Đã gửi lựa chọn suất trẻ em lúc 09:18 · Khách xác nhận 12 suất · Chờ bổ sung vào phụ lục đoàn."], ["FB-269", "Thay điểm đón xe đoàn", "Phạm Ngọc Anh · Hoàn tất", "Điểm đón mới đã cập nhật cho lái xe, điều phối và mã QR của trưởng đoàn; không phát sinh chi phí."]].map(([code, content, owner, detail]) => <details key={code} className="rounded-xl border border-[#e0e6e2] p-3 open:border-[#91aa9f]"><summary className="cursor-pointer list-none"><p className="text-xs font-black text-[#708078]">{code}</p><p className="mt-1 font-bold">{content}</p><p className="mt-1 text-xs text-[#7b8881]">{owner}</p></summary><p className="mt-3 border-t border-[#e4e9e6] pt-3 text-xs leading-5 text-[#5f7068]">{detail}</p></details>)}</div></article></section>
  </div>;
}
